[project]
name = "qbittorrent-auto-delete"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28",
    "schedule>=1.2",
]

[project.scripts]
qbittorrent-auto-delete = "qbittorrent_auto_delete.main:cli"

[tool.setuptools.packages.find]
where = ["src/main/python"]

[build-system]
requires = ["setuptools"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]